feat: ✨ update readme if necessary

diff --git a/.githooks/post-commit b/.githooks/post-commit
--- a/.githooks/post-commit
+++ b/.githooks/post-commit
@@ -1,15 +1,20 @@
 #!/bin/bash
 
+set -e
+
 # Load setup functions
 if [ -f "./setupscripts/setup_functions.sh" ]; then
+  echo "Found setup scripts"
   . ./setupscripts/setup_functions.sh
-elif [ "$0" != "./setupscripts/setup" ]; then
-  error "Please navigate to the root dotfiles directory and run ./setupscripts/setup"
+else
+  echo "Invalid path to setupscripts"
   exit 1
 fi
 
-# Update README.md
-cat << EOF > README.md
+# Write README to temp first
+TEMP=$(mktemp)
+
+cat << 'EOF' > "$TEMP"
 # Dotfiles
 
 [![test-scripts](https://github.com/aaatipamula/dotfiles/actions/workflows/test.yml/badge.svg)](https://github.com/aaatipamula/dotfiles/actions/workflows/test.yml)
@@ -25,14 +30,23 @@ This repo hosts my [dotfiles](https://missing.csail.mit.edu/2019/dotfiles/) for 
 
 Run the two following commands to get started.
 
-```bash
+\`\`\`bash
 git clone https://github.com/aaatipamula/dotfiles.git ~
 cd ~/dotfiles && ./setupscripts/setup
-```
+\`\`\`
 
-The following options are availabile for `setup`:
+The following options are availabile for \`setup\`:
 
-```
+\`\`\`
 $(help_command nocolor)
-```
+\`\`\`
 EOF
+
+# Only update and re-stage if content changed
+if ! diff -q "$README" "$TEMP" > /dev/null 2>&1; then
+  mv "$TEMP" "README.md"
+  git add "README.md"
+  git commit -m "Post-commit update README.md"
+fi
+
+exit 0
